name: Laravel CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "feature/**" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout project
      - name: Checkout code
        uses: actions/checkout@v4

      # Install PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_sqlite, sqlite3

      # Cache composer
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install composer
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # Prepare environment
      - name: Setup Application Environment
        run: cp .env.example .env

      - name: Configure SQLite for Tests
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      # Generate app key
      - name: Generate app key
        run: php artisan key:generate

      # Run migrations (in-memory)
      - name: Run Migrations
        run: php artisan migrate --force

      # Run tests
      - name: Run Tests
        run: php artisan test --parallel
